// 演员库 UI 文案（中/英）。纯数据模块，列表页与详情页共享。

export const actorLibraryCopy = {
  zh: {
    listKicker: "KIikis Talent",
    listTitle: "演员库",
    listSubtitle: "你的虚拟演员阵容。点击卡片查看完整人物设定与图片资产。",
    searchPlaceholder: "搜索演员、气质、可出演类型...",
    newActor: "新建演员",
    emptyTitle: "还没有演员",
    emptyBody: "像模特公司一样建立你的虚拟演员阵容：先用文字资料或头像创建第一位演员。",
    emptyAction: "创建第一位演员",
    loading: "正在加载演员阵容...",
    errorTitle: "演员库加载失败",
    retry: "重试",
    authKicker: "需要登录",
    authTitle: "登录后使用演员库",
    authBody: "演员库需要云端权限来区分个人资产与团队资产。",
    signIn: "去登录",
    actorCount: "位演员",
    teamBadge: "团队共享",
    privateBadge: "个人",
    statusReady: "已就绪",
    statusDraft: "草稿",
    statusAll: "全部",
    statusFilterLabel: "状态",
    tagFilterLabel: "标签",
    tagAll: "全部",
    sortLabel: "排序",
    sortUpdated: "最近更新",
    sortName: "姓名",
    sortPortrayals: "参演数",
    filterBarAria: "演员筛选",
    noResultTitle: "未匹配到演员",
    noResultBody: "调整搜索、状态或标签筛选条件后再试。",
    fallbackWarning: "演员结构化表暂不可用，当前为兜底存储；团队共享需部署演员库表结构。",
    createTitle: "新建演员",
    createTabText: "文字创建",
    createTabUpload: "上传头像",
    createName: "演员名称",
    createNamePlaceholder: "例如：Astra Lin",
    createAge: "年龄感",
    createAgePlaceholder: "例如：20代后半",
    createGender: "性别表达",
    createGenderPlaceholder: "例如：冷感女性 / 少年感男性",
    createEthnicity: "族裔 / 地域气质",
    createEthnicityPlaceholder: "例如：东亚都市感",
    createTemperament: "气质关键词（逗号分隔）",
    createTemperamentPlaceholder: "冷静, 危险, 克制",
    createRoles: "可出演类型（逗号分隔）",
    createRolesPlaceholder: "反派, 白切黑, 狼人女主",
    createBio: "演员简介",
    createBioPlaceholder: "只描述这个虚拟演员的基础视觉身份，不写剧情 canon。",
    createAvatarHint: "上传一张白底正面特写，创建后可在详情页生成三视图与表情组。",
    createAvatarPick: "选择图片",
    createAvatarSelected: "已选择",
    createSubmit: "创建演员",
    creating: "创建中...",
    createFailed: "创建演员失败。",
    createNameRequired: "请先填写演员名称。",
    uploadImageOnly: "请上传图片文件。",
    uploadLimit: "支持 JPEG / PNG / WebP，原文件最大 20MB，会自动压缩到 6MB 以内。",
    avatarProcessing: "正在处理图片（自动旋转 + 压缩）...",
    avatarUploading: "正在上传头像...",
    avatarInProgress: "头像还在处理或上传中，请稍候。",
    avatarErrorType: "仅支持 JPEG / PNG / WebP 格式的图片。",
    avatarErrorSize: "原文件不得超过 20MB。",
    avatarErrorDecode: "图片解码失败，请尝试其他图片。",
    avatarErrorUpload: "头像上传失败，请稍后重试。",
    editTitle: "编辑演员资料",
    editSubmit: "保存修改",
    editing: "保存中...",
    editFailed: "保存修改失败。",
    editAvatarReplace: "更换头像",
    editFacePlaceholder: "例如：方圆脸、浓眉、内双",
    editHairPlaceholder: "例如：齐肩直发、自然黑",
    editBodyPlaceholder: "例如：高挑偏瘦、长腿",
    editPromptPlaceholder: "可留空使用自动生成的提示词",
    visibilityLabel: "共享范围",
    visibilityPrivate: "仅创建者可见（private）",
    visibilityTeam: "团队成员可见（team）",
    visibilityPlatform: "全平台已登录用户可见（platform）",
    editNotCreator: "仅创建者可编辑演员基础资料。",
    cancel: "取消",
    backToLibrary: "演员库",
    detailLoading: "正在加载演员档案...",
    detailNotFound: "没有找到这位演员。",
    detailError: "演员档案加载失败。",
    detailErrorRetry: "重试",
    profileKicker: "人物设定",
    identityKicker: "身份",
    fieldAge: "年龄感",
    fieldGender: "性别表达",
    fieldEthnicity: "族裔 / 地域气质",
    fieldFace: "脸型与五官",
    fieldHair: "发型与发质",
    fieldBody: "体型与比例",
    fieldTemperament: "气质",
    fieldRoles: "可出演类型",
    fieldBio: "简介",
    fieldUpdatedAt: "最近更新",
    fieldPortrayalCount: "参演作品",
    fieldCompleteness: "身份资料完成度",
    completenessValue: (filled: number, total: number, percent: number) => `${filled}/${total} · ${percent}%`,
    playableTypesLabel: "可扮演类型",
    promptBase: "基础 Prompt",
    promptNegative: "Negative Prompt",
    promptTechnical: "技术提示词",
    promptTechnicalHint: "默认折叠，不影响首屏人物设定阅读。",
    promptExpand: "展开",
    promptCollapse: "收起",
    copy: "复制",
    copied: "已复制",
    assetsKicker: "图片资产",
    mainVisual: "主视觉",
    noMainVisual: "暂无主视觉。上传头像或生成头像后会显示在这里。",
    generate: "生成",
    regenerate: "重新生成",
    generating: "生成中",
    packEmpty: "尚未生成。点击生成，基于演员设定与主视觉产出这一组图片。",
    packError: "生成失败，已保留现有图片。",
    packLoadFailed: "历史版本暂时读取失败，可直接生成新版本。",
    viewOpen: "查看大图",
    versionPrimary: "主版本",
    versionSetPrimary: "设为主版本",
    versionPrimaryBadge: "主",
    versionHistory: "历史版本",
    versionHistoryEmpty: "该图组还没有历史版本。",
    versionCount: (n: number) => `${n} 个版本`,
    exportSheet: "合并导出参考表",
    exporting: "拼图导出中...",
    exportEmpty: "暂无可导出的图片。",
    exportFailed: "导出失败：图片跨域受限，请稍后重试。",
    exportDone: "参考表已导出。",
    sheetMainLabel: "主视觉",
    sheetViewLabels: ["正面", "侧面", "背面"],
    sheetExpressionLabels: ["表情 1", "表情 2", "表情 3", "表情 4", "表情 5", "表情 6", "表情 7", "表情 8", "表情 9"],
    sheetDetailLabels: ["细节 1", "细节 2"],
    sheetFooter: "KIikis StoryFlow · 虚拟演员参考表",
    portrayalsKicker: "参演作品",
    portrayalsEmpty: "这位演员还没有参演任何作品。",
    portrayalsError: "参演作品读取失败。",
    portrayalUntitled: "未命名角色",
    portrayalUntitledWork: "未关联作品",
    portrayalProject: "作品",
    portrayalCharacter: "角色",
    portrayalUniverse: "世界观",
    portrayalCostume: "造型方向",
    portrayalVisual: "形象版本",
    portrayalReusable: "可复用",
    portrayalReusableBadge: "可复用形象",
    portrayalNotReusableBadge: "仅本作品",
    portrayalUpdatedAt: (iso: string) => iso ? new Date(iso).toLocaleDateString("zh-CN") : "—",
    notProvided: "未填写",
  },
  en: {
    listKicker: "KIikis Talent",
    listTitle: "Actor Library",
    listSubtitle: "Your virtual talent roster. Open a card for the full profile and image assets.",
    searchPlaceholder: "Search actors, temperament, roles...",
    newActor: "New actor",
    emptyTitle: "No actors yet",
    emptyBody: "Build your virtual roster like a talent agency — create the first actor from text or a headshot.",
    emptyAction: "Create the first actor",
    loading: "Loading the roster...",
    errorTitle: "Failed to load Actor Library",
    retry: "Retry",
    authKicker: "Login required",
    authTitle: "Sign in to use Actor Library",
    authBody: "Actor Library needs cloud access to separate personal and team assets.",
    signIn: "Sign in",
    actorCount: "actors",
    teamBadge: "Team",
    privateBadge: "Personal",
    statusReady: "Ready",
    statusDraft: "Draft",
    statusAll: "All",
    statusFilterLabel: "Status",
    tagFilterLabel: "Tags",
    tagAll: "All",
    sortLabel: "Sort",
    sortUpdated: "Last updated",
    sortName: "Name",
    sortPortrayals: "Portrayals",
    filterBarAria: "Filter actors",
    noResultTitle: "No matching actors",
    noResultBody: "Adjust your search, status, or tag filter and try again.",
    fallbackWarning: "Structured actor tables are unavailable; a fallback storage is in use.",
    createTitle: "New actor",
    createTabText: "From text",
    createTabUpload: "Upload headshot",
    createName: "Actor name",
    createNamePlaceholder: "Example: Astra Lin",
    createAge: "Age impression",
    createAgePlaceholder: "Example: late 20s",
    createGender: "Gender expression",
    createGenderPlaceholder: "Example: cold feminine / boyish masculine",
    createEthnicity: "Ethnicity / regional tone",
    createEthnicityPlaceholder: "Example: East Asian urban tone",
    createTemperament: "Temperament tags (comma separated)",
    createTemperamentPlaceholder: "calm, dangerous, restrained",
    createRoles: "Playable roles (comma separated)",
    createRolesPlaceholder: "villain, hidden heir, werewolf heroine",
    createBio: "Actor bio",
    createBioPlaceholder: "Describe only the base visual identity, not story canon.",
    createAvatarHint: "Upload a front-facing portrait on white. Three-views and expressions can be generated afterwards.",
    createAvatarPick: "Choose image",
    createAvatarSelected: "Selected",
    createSubmit: "Create actor",
    creating: "Creating...",
    createFailed: "Failed to create actor.",
    createNameRequired: "Name the actor first.",
    uploadImageOnly: "Please upload an image file.",
    uploadLimit: "Supports JPEG / PNG / WebP up to 20MB; auto-compressed to <= 6MB.",
    avatarProcessing: "Processing image (auto-rotate + compress)...",
    avatarUploading: "Uploading avatar...",
    avatarInProgress: "Avatar is still processing or uploading. Please wait.",
    avatarErrorType: "Only JPEG / PNG / WebP images are supported.",
    avatarErrorSize: "Raw files must be under 20MB.",
    avatarErrorDecode: "Failed to decode image. Try another one.",
    avatarErrorUpload: "Avatar upload failed. Please retry.",
    editTitle: "Edit Actor Profile",
    editSubmit: "Save Changes",
    editing: "Saving...",
    editFailed: "Failed to save changes.",
    editAvatarReplace: "Replace Avatar",
    editFacePlaceholder: "e.g. square-round face, bold brows, monolid",
    editHairPlaceholder: "e.g. shoulder-length straight, natural black",
    editBodyPlaceholder: "e.g. tall and slim, long legs",
    editPromptPlaceholder: "Leave empty to use auto-generated prompt",
    visibilityLabel: "Visibility",
    visibilityPrivate: "Private (creator only)",
    visibilityTeam: "Team (members)",
    visibilityPlatform: "Platform (all signed-in users)",
    editNotCreator: "Only the creator can edit base actor profile.",
    cancel: "Cancel",
    backToLibrary: "Actor Library",
    detailLoading: "Loading actor profile...",
    detailNotFound: "Actor not found.",
    detailError: "Failed to load actor profile.",
    detailErrorRetry: "Retry",
    profileKicker: "Profile",
    identityKicker: "Identity",
    fieldAge: "Age impression",
    fieldGender: "Gender expression",
    fieldEthnicity: "Ethnicity / regional tone",
    fieldFace: "Face & features",
    fieldHair: "Hair",
    fieldBody: "Body & proportions",
    fieldTemperament: "Temperament",
    fieldRoles: "Playable roles",
    fieldBio: "Bio",
    fieldUpdatedAt: "Last updated",
    fieldPortrayalCount: "Portrayals",
    fieldCompleteness: "Identity completeness",
    completenessValue: (filled: number, total: number, percent: number) => `${filled}/${total} · ${percent}%`,
    playableTypesLabel: "Playable types",
    promptBase: "Base Prompt",
    promptNegative: "Negative Prompt",
    promptTechnical: "Technical prompts",
    promptTechnicalHint: "Collapsed by default so the profile stays scannable.",
    promptExpand: "Expand",
    promptCollapse: "Collapse",
    copy: "Copy",
    copied: "Copied",
    assetsKicker: "Image assets",
    mainVisual: "Main visual",
    noMainVisual: "No main visual yet. It appears after an avatar is uploaded or generated.",
    generate: "Generate",
    regenerate: "Regenerate",
    generating: "Generating",
    packEmpty: "Not generated yet. Generate this set from the actor profile and main visual.",
    packError: "Generation failed. Existing images were kept.",
    packLoadFailed: "Could not load previous versions. You can still generate new ones.",
    viewOpen: "Open full size",
    versionPrimary: "Primary",
    versionSetPrimary: "Set as primary",
    versionPrimaryBadge: "P",
    versionHistory: "Version history",
    versionHistoryEmpty: "No previous versions for this pack yet.",
    versionCount: (n: number) => `${n} version${n === 1 ? "" : "s"}`,
    exportSheet: "Export reference sheet",
    exporting: "Composing sheet...",
    exportEmpty: "Nothing to export yet.",
    exportFailed: "Export failed: images are cross-origin restricted. Try again later.",
    exportDone: "Reference sheet exported.",
    sheetMainLabel: "Main visual",
    sheetViewLabels: ["Front", "Side", "Back"],
    sheetExpressionLabels: ["Expr 1", "Expr 2", "Expr 3", "Expr 4", "Expr 5", "Expr 6", "Expr 7", "Expr 8", "Expr 9"],
    sheetDetailLabels: ["Detail 1", "Detail 2"],
    sheetFooter: "KIikis StoryFlow · Virtual Actor Reference",
    portrayalsKicker: "Portrayals",
    portrayalsEmpty: "This actor has not appeared in any project yet.",
    portrayalsError: "Failed to load portrayals.",
    portrayalUntitled: "Untitled role",
    portrayalUntitledWork: "Unlinked work",
    portrayalProject: "Work",
    portrayalCharacter: "Character",
    portrayalUniverse: "Universe",
    portrayalCostume: "Costume",
    portrayalVisual: "Look",
    portrayalReusable: "Reusable",
    portrayalReusableBadge: "Reusable look",
    portrayalNotReusableBadge: "This work only",
    portrayalUpdatedAt: (iso: string) => (iso ? new Date(iso).toLocaleDateString("en-US") : "—"),
    notProvided: "Not provided",
  },
} as const;

export type ActorLibraryCopy = (typeof actorLibraryCopy)["zh"] | (typeof actorLibraryCopy)["en"];
