// 后台管理系统前端文案，锁定中文简体，不走 i18n provider
export const zh = {
  brand: "Kiikis 后台",
  nav: {
    overview: "概览",
    users: "用户管理",
    aiPrompts: "AI 指令",
    admins: "管理员角色",
    auditLog: "审计日志",
    logout: "登出",
  },
  role: {
    super_admin: "超级管理员",
    operator: "运营",
    viewer: "只读审核",
  },
  common: {
    loading: "加载中...",
    unauthorized: "无权限访问",
    unauthenticated: "请先登录",
    save: "保存",
    cancel: "取消",
    confirm: "确认",
    reset: "重置",
    search: "搜索",
    refresh: "刷新",
    empty: "暂无数据",
    error: "出错了",
    back: "返回",
  },
  overview: {
    title: "概览",
    totalUsers: "用户总数",
    newUsersToday: "今日新增",
    totalGenerations: "生成任务总数",
    comingSoon: "运营看板即将上线",
  },
  users: {
    title: "用户管理",
    listBody: "查看与管理系统所有用户",
    colEmail: "邮箱",
    colName: "名称",
    colSignedUp: "注册时间",
    colPlan: "套餐",
    colCredits: "积分",
    colStatus: "状态",
    statusActive: "正常",
    statusBanned: "已封禁",
    filterPlan: "套餐",
    filterStatus: "状态",
    detail: {
      basicInfo: "基本信息",
      creditsAccount: "积分账户",
      balance: "当前余额",
      monthlyLimit: "月度上限",
      period: "当前周期",
      plan: "套餐",
      displayName: "显示名称",
      accountStatus: "账号状态",
      recentActivity: "最近活动",
      adjustCredits: "调整积分",
      charge: "充值",
      deduct: "扣减",
      resetCredits: "重置至上限",
      ban: "封禁",
      unban: "解封",
      banConfirm: "封禁该用户？该用户将无法登录",
      deductConfirm: "扣减积分？此操作不可撤销",
    },
  },
  aiPrompts: {
    title: "AI 指令编辑",
    warning: "修改将影响所有用户的 AI 生成质量",
    tabRules: "顶层 Rules",
    tabTasks: "任务指令",
    tabOverrides: "全局注入",
    save: "保存",
    resetDefault: "重置默认",
    versionHistory: "版本历史",
    rollback: "回滚到此版本",
    diff: "对比",
    saveConfirm: "确认保存？修改将立即影响所有 AI 生成",
    overrideScope: "作用范围",
    scopeGlobal: "全局",
    scopeTaskType: "指定任务",
    position: "位置",
    positionPrepend: "前置",
    positionAppend: "后置",
    injectionText: "注入片段",
    enabled: "启用",
    newOverride: "新建注入",
  },
  admins: {
    title: "管理员角色",
    addAdmin: "添加管理员",
    colEmail: "邮箱",
    colRole: "角色",
    colCreatedAt: "添加时间",
  },
  auditLog: {
    title: "审计日志",
    colTime: "时间",
    colAdmin: "操作人",
    colAction: "操作",
    colTarget: "对象",
    filterAction: "操作类型",
  },
} as const;

export type Zh = typeof zh;
