import { NextRequest, NextResponse } from "next/server";
import { authenticateRequest, hasServiceRoleConfig, serviceFetch } from "@/lib/supabase/server";
import { createAsset, listAssets, AssetError } from "@/lib/server/v2/assets";
import { assetErrorResponse } from "@/lib/server/v2/assets/http";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export async function GET(request: NextRequest) { try { const user = await authenticateRequest(request); if (!hasServiceRoleConfig()) throw new AssetError("service_unavailable", "Cloud data service is not configured."); const p = request.nextUrl.searchParams; const result = await listAssets({ fetcher: serviceFetch, userId: user.id, kind: p.get("kind"), status: p.get("status"), projectId: p.get("projectId") }); return NextResponse.json({ success: true, contractVersion: "2.0.0-alpha.1", ...result }); } catch (error) { return routeError(error, "Unable to read assets."); } }
export async function POST(request: NextRequest) { try { const user = await authenticateRequest(request); if (!hasServiceRoleConfig()) throw new AssetError("service_unavailable", "Cloud data service is not configured."); const result = await createAsset({ fetcher: serviceFetch, userId: user.id, input: await request.json() }); return NextResponse.json({ success: true, contractVersion: "2.0.0-alpha.1", ...result }, { status: 201 }); } catch (error) { return routeError(error, "Unable to create asset."); } }
function routeError(error: unknown, fallback: string) { if (error instanceof Error && (error.message.includes("MISSING_AUTH_TOKEN") || error.message.includes("INVALID_AUTH_TOKEN"))) return NextResponse.json({ success: false, error: "Authentication is required.", code: "unauthenticated" }, { status: 401 }); return assetErrorResponse(error, fallback); }
