import type { ArtModelDescriptor } from "./types.ts";

export const ART_MODEL_CATALOG: ArtModelDescriptor[] = [
  {
    id: "flux-2-pro",
    label: "FLUX.2 Pro",
    family: "flux-2-pro",
    provider: "flux",
    capabilities: ["text-to-image", "image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "concept", "edit"],
    maxReferences: 8,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  {
    id: "flux-2-max",
    label: "FLUX.2 Max",
    family: "flux-2-max",
    provider: "flux",
    capabilities: ["text-to-image", "image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "concept", "edit"],
    maxReferences: 8,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
  },
  {
    id: "black-forest-labs/flux-2-flex/text-to-image",
    label: "FLUX 2 Flex · 文生图",
    family: "flux-2-flex",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "flux2-flex-text",
  },
  {
    id: "black-forest-labs/flux-2-flex/edit",
    label: "FLUX 2 Flex · 参考图生成",
    family: "flux-2-flex",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 8,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "flux2-flex-edit",
  },
  {
    id: "openai/gpt-image-2.5-flare/text-to-image",
    label: "GPT Image 2.5 Flare · 文生图",
    family: "gpt-image-2.5-flare",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt25-text",
  },
  {
    id: "openai/gpt-image-2.5-flare/edit",
    label: "GPT Image 2.5 Flare · 参考图生成",
    family: "gpt-image-2.5-flare",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 16,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt25-edit",
  },
  {
    id: "openai/gpt-image-2.5-sunburst/text-to-image",
    label: "GPT Image 2.5 Sunburst · 文生图",
    family: "gpt-image-2.5-sunburst",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt25-text",
  },
  {
    id: "openai/gpt-image-2.5-sunburst/edit",
    label: "GPT Image 2.5 Sunburst · 参考图生成",
    family: "gpt-image-2.5-sunburst",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 16,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt25-edit",
  },
  {
    id: "openai/gpt-image-2/text-to-image",
    label: "GPT Image 2 · 文生图",
    family: "gpt-image-2",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt-text",
  },
  {
    id: "openai/gpt-image-2/edit",
    label: "GPT Image 2 · 参考图生成",
    family: "gpt-image-2",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 10,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "gpt-edit",
  },
  {
    id: "xai/grok-imagine-image-2.0/text-to-image",
    label: "Grok Imagine 2.0 · 文生图",
    family: "grok-imagine-2.0",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "grok-text",
  },
  {
    id: "xai/grok-imagine-image-2.0/edit",
    label: "Grok Imagine 2.0 · 参考图生成",
    family: "grok-imagine-2.0",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 3,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "grok-edit",
  },
  {
    id: "google/nano-banana-2.1/text-to-image",
    label: "Gemini · Nano Banana 2.1 · 文生图",
    family: "gemini-nano-banana-2.1",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "banana21-text",
  },
  {
    id: "google/nano-banana-2.1/edit",
    label: "Gemini · Nano Banana 2.1 · 参考图生成",
    family: "gemini-nano-banana-2.1",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 14,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "banana21-edit",
  },
  {
    id: "google/nano-banana-pro/text-to-image-ultra",
    label: "Gemini · Nano Banana Pro Ultra · 文生图",
    family: "gemini-nano-banana-pro-ultra",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "banana-ultra-text",
  },
  {
    id: "google/nano-banana-pro/edit-ultra",
    label: "Gemini · Nano Banana Pro Ultra · 参考图生成",
    family: "gemini-nano-banana-pro-ultra",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 10,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "banana-edit",
  },
  {
    id: "bytedance/seedream-v5.0-flash/text-to-image",
    label: "Seedream 5.0 Flash · 文生图",
    family: "seedream-5.0-flash",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "seedream-text",
  },
  {
    id: "bytedance/seedream-v5.0-flash/edit",
    label: "Seedream 5.0 Flash · 参考图生成",
    family: "seedream-5.0-flash",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 10,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "seedream-edit",
  },
  {
    id: "bytedance/seedream-v5.0-pro/text-to-image",
    label: "Seedream 5.0 Pro · 文生图",
    family: "seedream-5.0-pro",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "seedream-text",
  },
  {
    id: "bytedance/seedream-v5.0-pro/edit",
    label: "Seedream 5.0 Pro · 参考图生成",
    family: "seedream-5.0-pro",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 10,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "seedream-edit",
  },
  {
    id: "hidream-o1-1.5/text-to-image",
    label: "HiDream O1 1.5 · 文生图",
    family: "hidream-o1-1.5",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "hidream-text",
  },
  {
    id: "hidream-o1-1.5/edit",
    label: "HiDream O1 1.5 · 参考图生成",
    family: "hidream-o1-1.5",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 8,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "hidream-edit",
  },
  {
    id: "reve-ai/reve-2.1/text-to-image",
    label: "Reve 2.1 · 4K 文生图",
    family: "reve-2.1",
    provider: "atlas",
    capabilities: ["text-to-image"],
    recommendedFor: ["reference_sheet", "concept"],
    maxReferences: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "reve-text",
  },
  {
    id: "reve-ai/reve-2.1/edit",
    label: "Reve 2.1 · 单图精修",
    family: "reve-2.1",
    provider: "atlas",
    capabilities: ["image-edit"],
    recommendedFor: ["variant", "edit"],
    maxReferences: 1,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "reve-edit",
  },
  {
    id: "reve-ai/reve-2.1/remix",
    label: "Reve 2.1 · 多图融合",
    family: "reve-2.1-remix",
    provider: "atlas",
    capabilities: ["image-edit", "multi-reference"],
    recommendedFor: ["reference_sheet", "variant", "edit"],
    maxReferences: 6,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    atlasProfile: "reve-remix",
  },
];

export function findArtModel(modelId: string) {
  return ART_MODEL_CATALOG.find((model) => model.id === modelId) || null;
}

export function listArtModels(provider: "atlas" | "flux", capability: "text-to-image" | "image-edit") {
  return ART_MODEL_CATALOG.filter((model) => model.provider === provider && model.capabilities.includes(capability));
}

export function findDefaultArtModel(provider: "atlas" | "flux", capability: "text-to-image" | "image-edit") {
  const defaultId = provider === "atlas"
    ? capability === "image-edit" ? "openai/gpt-image-2.5-flare/edit" : "openai/gpt-image-2.5-flare/text-to-image"
    : "flux-2-pro";
  return findArtModel(defaultId);
}
